{"uid":"65aebcecf934a363","name":"Создание двух простых моделей с одинаковыми именами, проверка и удаление","fullName":"Test_Cases.test_model.TestModel#test_model2","historyId":"922ff6b4c29c587b1078754ad59f1c7a","time":{"start":1690973260159,"stop":1690973260159,"duration":0},"description":"Проверка работоспособности раздела 'Модели'","descriptionHtml":"<p>Проверка работоспособности раздела 'Модели'</p>\n","status":"broken","statusMessage":"ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_linux64.zip","statusTrace":"request = <SubRequest 'get_webdriver' for <Function test_homepage>>\nget_chrome_options = <selenium.webdriver.chrome.options.Options object at 0x7feeaa5b07c0>\n\n    @pytest.fixture(scope='session')\n    def get_webdriver(request, get_chrome_options):\n        options = get_chrome_options\n>       driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)\n\nTest_Cases/conftest.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/chrome.py:39: in install\n    driver_path = self._get_driver_path(self.driver)\n/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/manager.py:30: in _get_driver_path\n    file = self._download_manager.download_file(driver.get_url())\n/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/download_manager.py:28: in download_file\n    response = self._http_client.get(url)\n/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/http.py:33: in get\n    self.validate_response(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresp = <Response [404]>\n\n    @staticmethod\n    def validate_response(resp: requests.Response):\n        status_code = resp.status_code\n        if status_code == 404:\n>           raise ValueError(f\"There is no such driver by url {resp.url}\")\nE           ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_linux64.zip\n\n/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/http.py:16: ValueError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"get_chrome_options","time":{"start":1690973259082,"stop":1690973259082,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"get_webdriver","time":{"start":1690973259082,"stop":1690973260056,"duration":974},"status":"broken","statusMessage":"ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_linux64.zip\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 908, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/LTA_TESTS/LTA_TESTS/Test_Cases/conftest.py\", line 34, in get_webdriver\n    driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/chrome.py\", line 39, in install\n    driver_path = self._get_driver_path(self.driver)\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/manager.py\", line 30, in _get_driver_path\n    file = self._download_manager.download_file(driver.get_url())\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/download_manager.py\", line 28, in download_file\n    response = self._http_client.get(url)\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/http.py\", line 33, in get\n    self.validate_response(resp)\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/http.py\", line 16, in validate_response\n    raise ValueError(f\"There is no such driver by url {resp.url}\")\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"afterStages":[],"labels":[{"name":"parentSuite","value":"Test_Cases"},{"name":"suite","value":"test_model"},{"name":"subSuite","value":"TestModel"},{"name":"host","value":"fv-az176-343"},{"name":"thread","value":"2377-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"Test_Cases.test_model"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":6,"unknown":0,"total":9},"items":[{"uid":"ed385099aef93766","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/34//#testresult/ed385099aef93766","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5606d2d87783 <unknown>\n#1 0x5606d2ab3917 <unknown>\n#2 0x5606d2af231b <unknown>\n#3 0x5606d2af2411 <unknown>\n#4 0x5606d2b2d674 <unknown>\n#5 0x5606d2b12e2d <unknown>\n#6 0x5606d2b2b0d9 <unknown>\n#7 0x5606d2b12bd3 <unknown>\n#8 0x5606d2ae6a7b <unknown>\n#9 0x5606d2ae781e <unknown>\n#10 0x5606d2d48e98 <unknown>\n#11 0x5606d2d4cd67 <unknown>\n#12 0x5606d2d5732c <unknown>\n#13 0x5606d2d4d993 <unknown>\n#14 0x5606d2d1c827 <unknown>\n#15 0x5606d2d718a8 <unknown>\n#16 0x5606d2d71a36 <unknown>\n#17 0x5606d2d805f3 <unknown>\n#18 0x7fe15aef0b43 <unknown>","time":{"start":1690972646336,"stop":1690972661752,"duration":15416}},{"uid":"3ba52182a35dba51","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/33//#testresult/3ba52182a35dba51","status":"broken","statusDetails":"ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_linux64.zip","time":{"start":1690971483272,"stop":1690971483272,"duration":0}},{"uid":"87e4e598cbfab88f","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/32//#testresult/87e4e598cbfab88f","status":"passed","time":{"start":1682507067614,"stop":1682507081508,"duration":13894}},{"uid":"e055452f81a5ba80","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/32//#testresult/e055452f81a5ba80","status":"passed","time":{"start":1682505656827,"stop":1682505670640,"duration":13813}},{"uid":"c1d78f8299b7410","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/31//#testresult/c1d78f8299b7410","status":"passed","time":{"start":1682503889270,"stop":1682503903148,"duration":13878}},{"uid":"856f69a7ffa2f9eb","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/30//#testresult/856f69a7ffa2f9eb","status":"passed","time":{"start":1682503333259,"stop":1682503347398,"duration":14139}},{"uid":"343ae946d8703444","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/29//#testresult/343ae946d8703444","status":"passed","time":{"start":1682502704211,"stop":1682502718033,"duration":13822}},{"uid":"a2d0e16f9f4d897c","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/28//#testresult/a2d0e16f9f4d897c","status":"passed","time":{"start":1682500536337,"stop":1682500550210,"duration":13873}}]},"tags":[]},"source":"65aebcecf934a363.json","parameterValues":[]}