{"uuid": "bf1a33af-e771-414b-a46b-f6b9fa700af6", "children": ["5b3a4ec6-4e80-43fa-a22f-6bfd23dec50d"], "befores": [{"name": "authorization", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/_pytest/fixtures.py\", line 908, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/maksim/PycharmProjects/LTA_TESTS/Test_Cases/conftest.py\", line 50, in authorization\n    wait.until(ec.url_to_be('http://185.221.152.176/hmi/17'))\n  File \"/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1678792097954, "stop": 1678792120027}], "start": 1678792097954, "stop": 1678792120165}