{"uid":"a8728c6b04dec7f6","name":"Создание корневого объекта, добавление в него двух объектов по модели Directory с уникальными именами. Удаление одного дочернего объекта, проверка. Удаление корневого объекта","fullName":"Test_Cases.test_object.TestObject#test_object4","historyId":"474187683b9a0b71a304c3b21556d477","time":{"start":1690975072505,"stop":1690975072505,"duration":0},"description":"Проверка работоспособности раздела 'Объекты'","descriptionHtml":"<p>Проверка работоспособности раздела 'Объекты'</p>\n","status":"broken","statusMessage":"ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_linux64.zip","statusTrace":"request = <SubRequest 'get_webdriver' for <Function test_homepage>>\nget_chrome_options = <selenium.webdriver.chrome.options.Options object at 0x7f9d3ca18160>\n\n    @pytest.fixture(scope='session')\n    def get_webdriver(request, get_chrome_options):\n        options = get_chrome_options\n>       driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)\n\nTest_Cases/conftest.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/chrome.py:39: in install\n    driver_path = self._get_driver_path(self.driver)\n/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/manager.py:30: in _get_driver_path\n    file = self._download_manager.download_file(driver.get_url())\n/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/download_manager.py:28: in download_file\n    response = self._http_client.get(url)\n/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/http.py:33: in get\n    self.validate_response(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresp = <Response [404]>\n\n    @staticmethod\n    def validate_response(resp: requests.Response):\n        status_code = resp.status_code\n        if status_code == 404:\n>           raise ValueError(f\"There is no such driver by url {resp.url}\")\nE           ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_linux64.zip\n\n/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/http.py:16: ValueError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"get_chrome_options","time":{"start":1690975069333,"stop":1690975069333,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"get_webdriver","time":{"start":1690975069334,"stop":1690975072348,"duration":3014},"status":"broken","statusMessage":"ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_linux64.zip\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 908, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/LTA_TESTS/LTA_TESTS/Test_Cases/conftest.py\", line 34, in get_webdriver\n    driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/chrome.py\", line 39, in install\n    driver_path = self._get_driver_path(self.driver)\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/manager.py\", line 30, in _get_driver_path\n    file = self._download_manager.download_file(driver.get_url())\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/download_manager.py\", line 28, in download_file\n    response = self._http_client.get(url)\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/http.py\", line 33, in get\n    self.validate_response(resp)\n  File \"/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/webdriver_manager/core/http.py\", line 16, in validate_response\n    raise ValueError(f\"There is no such driver by url {resp.url}\")\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"afterStages":[],"labels":[{"name":"parentSuite","value":"Test_Cases"},{"name":"suite","value":"test_object"},{"name":"subSuite","value":"TestObject"},{"name":"host","value":"fv-az362-960"},{"name":"thread","value":"2198-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"Test_Cases.test_object"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":6,"skipped":0,"passed":6,"unknown":0,"total":12},"items":[{"uid":"4d05b09cc0feae96","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/37//#testresult/4d05b09cc0feae96","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55b34f07c783 <unknown>\n#1 0x55b34eda8917 <unknown>\n#2 0x55b34edd3978 <unknown>\n#3 0x55b34edd09c9 <unknown>\n#4 0x55b34ee10a13 <unknown>\n#5 0x55b34ee1015f <unknown>\n#6 0x55b34ee07bd3 <unknown>\n#7 0x55b34eddba7b <unknown>\n#8 0x55b34eddc81e <unknown>\n#9 0x55b34f03de98 <unknown>\n#10 0x55b34f041d67 <unknown>\n#11 0x55b34f04c32c <unknown>\n#12 0x55b34f042993 <unknown>\n#13 0x55b34f011827 <unknown>\n#14 0x55b34f0668a8 <unknown>\n#15 0x55b34f066a36 <unknown>\n#16 0x55b34f0755f3 <unknown>\n#17 0x7f282c34ab43 <unknown>","time":{"start":1690974900662,"stop":1690974900662,"duration":0}},{"uid":"e49d82b3d3c0eb55","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/36//#testresult/e49d82b3d3c0eb55","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/app-root/app-admin-layout/div/app-menu/aside/nav/ul/li[5]/a\"}\n  (Session info: headless chrome=115.0.5790.102); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x5618697cd783 <unknown>\n#1 0x5618694f9917 <unknown>\n#2 0x56186953831b <unknown>\n#3 0x561869538411 <unknown>\n#4 0x561869573674 <unknown>\n#5 0x561869558e2d <unknown>\n#6 0x5618695710d9 <unknown>\n#7 0x561869558bd3 <unknown>\n#8 0x56186952ca7b <unknown>\n#9 0x56186952d81e <unknown>\n#10 0x56186978ee98 <unknown>\n#11 0x561869792d67 <unknown>\n#12 0x56186979d32c <unknown>\n#13 0x561869793993 <unknown>\n#14 0x561869762827 <unknown>\n#15 0x5618697b78a8 <unknown>\n#16 0x5618697b7a36 <unknown>\n#17 0x5618697c65f3 <unknown>\n#18 0x7fdff123bb43 <unknown>","time":{"start":1690973765999,"stop":1690973766017,"duration":18}},{"uid":"69d3ff5d370d11ec","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/35//#testresult/69d3ff5d370d11ec","status":"broken","statusDetails":"ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_linux64.zip","time":{"start":1690973260252,"stop":1690973260252,"duration":0}},{"uid":"6c01e87f9facd486","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/34//#testresult/6c01e87f9facd486","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"/html/body/app-root/app-admin-layout/div/app-menu/aside/nav/ul/li[5]/a\"}\n  (Session info: headless chrome=115.0.5790.110)\nStacktrace:\n#0 0x5606d2d87783 <unknown>\n#1 0x5606d2ab3917 <unknown>\n#2 0x5606d2af231b <unknown>\n#3 0x5606d2af2411 <unknown>\n#4 0x5606d2b2d674 <unknown>\n#5 0x5606d2b12e2d <unknown>\n#6 0x5606d2b2b0d9 <unknown>\n#7 0x5606d2b12bd3 <unknown>\n#8 0x5606d2ae6a7b <unknown>\n#9 0x5606d2ae781e <unknown>\n#10 0x5606d2d48e98 <unknown>\n#11 0x5606d2d4cd67 <unknown>\n#12 0x5606d2d5732c <unknown>\n#13 0x5606d2d4d993 <unknown>\n#14 0x5606d2d1c827 <unknown>\n#15 0x5606d2d718a8 <unknown>\n#16 0x5606d2d71a36 <unknown>\n#17 0x5606d2d805f3 <unknown>\n#18 0x7fe15aef0b43 <unknown>","time":{"start":1690972692940,"stop":1690972692955,"duration":15}},{"uid":"a52fa20e1cc06e5b","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/33//#testresult/a52fa20e1cc06e5b","status":"broken","statusDetails":"ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_linux64.zip","time":{"start":1690971483345,"stop":1690971483345,"duration":0}},{"uid":"ac7a554325e7b984","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/32//#testresult/ac7a554325e7b984","status":"passed","time":{"start":1682507203459,"stop":1682507218887,"duration":15428}},{"uid":"2f6f503931d6442e","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/32//#testresult/2f6f503931d6442e","status":"passed","time":{"start":1682505789066,"stop":1682505804422,"duration":15356}},{"uid":"b0fc29220267bad7","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/31//#testresult/b0fc29220267bad7","status":"passed","time":{"start":1682504031652,"stop":1682504047192,"duration":15540}},{"uid":"7bca7f507bd4057e","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/30//#testresult/7bca7f507bd4057e","status":"passed","time":{"start":1682503494738,"stop":1682503511351,"duration":16613}},{"uid":"498d88ba6401c328","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/29//#testresult/498d88ba6401c328","status":"passed","time":{"start":1682502836813,"stop":1682502851796,"duration":14983}},{"uid":"2ab554150034fe2c","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/28//#testresult/2ab554150034fe2c","status":"passed","time":{"start":1682500673213,"stop":1682500688726,"duration":15513}}]},"tags":[]},"source":"a8728c6b04dec7f6.json","parameterValues":[]}