{"uid":"7c52aaa85451e8fa","name":"Создание простой модели, добавление в нее компонентов, проверка и удаление","fullName":"Test_Cases.test_model.TestModel#test_model1","historyId":"ea9762191b37f571ad04b7f5ab0b1537","time":{"start":1707026951094,"stop":1707026951094,"duration":0},"description":"Проверка работоспособности раздела 'Модели'","descriptionHtml":"<p>Проверка работоспособности раздела 'Модели'</p>\n","status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x562157d74d93 <unknown>\n#1 0x562157a58337 <unknown>\n#2 0x562157a8cbc0 <unknown>\n#3 0x562157a88765 <unknown>\n#4 0x562157ad2b7c <unknown>\n#5 0x562157ac61e3 <unknown>\n#6 0x562157a96135 <unknown>\n#7 0x562157a9713e <unknown>\n#8 0x562157d38e4b <unknown>\n#9 0x562157d3cdfa <unknown>\n#10 0x562157d256d5 <unknown>\n#11 0x562157d3da6f <unknown>\n#12 0x562157d0969f <unknown>\n#13 0x562157d62098 <unknown>\n#14 0x562157d62262 <unknown>\n#15 0x562157d73f34 <unknown>\n#16 0x7f821a694ac3 <unknown>","statusTrace":"get_chrome_options = <selenium.webdriver.chrome.options.Options object at 0x7f1941e68e10>\n\n    @pytest.fixture(scope='session')\n    def get_webdriver(get_chrome_options):\n        options = get_chrome_options\n>       driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=options)\n\nTest_Cases/conftest.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:205: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:289: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:344: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f1943dd2810>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"session not created\",\"message\":\"session not created: Chrome failed to sta...\\\\n#14 0x562157d62262 \\\\u003Cunknown>\\\\n#15 0x562157d73f34 \\\\u003Cunknown>\\\\n#16 0x7f821a694ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\nE         (session not created: DevToolsActivePort file doesn't exist)\nE         (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nE       Stacktrace:\nE       #0 0x562157d74d93 <unknown>\nE       #1 0x562157a58337 <unknown>\nE       #2 0x562157a8cbc0 <unknown>\nE       #3 0x562157a88765 <unknown>\nE       #4 0x562157ad2b7c <unknown>\nE       #5 0x562157ac61e3 <unknown>\nE       #6 0x562157a96135 <unknown>\nE       #7 0x562157a9713e <unknown>\nE       #8 0x562157d38e4b <unknown>\nE       #9 0x562157d3cdfa <unknown>\nE       #10 0x562157d256d5 <unknown>\nE       #11 0x562157d3da6f <unknown>\nE       #12 0x562157d0969f <unknown>\nE       #13 0x562157d62098 <unknown>\nE       #14 0x562157d62262 <unknown>\nE       #15 0x562157d73f34 <unknown>\nE       #16 0x7f821a694ac3 <unknown>\n\n/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:229: SessionNotCreatedException","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"get_webdriver","time":{"start":1707026950268,"stop":1707026951039,"duration":771},"status":"broken","statusMessage":"selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x562157d74d93 <unknown>\n#1 0x562157a58337 <unknown>\n#2 0x562157a8cbc0 <unknown>\n#3 0x562157a88765 <unknown>\n#4 0x562157ad2b7c <unknown>\n#5 0x562157ac61e3 <unknown>\n#6 0x562157a96135 <unknown>\n#7 0x562157a9713e <unknown>\n#8 0x562157d38e4b <unknown>\n#9 0x562157d3cdfa <unknown>\n#10 0x562157d256d5 <unknown>\n#11 0x562157d3da6f <unknown>\n#12 0x562157d0969f <unknown>\n#13 0x562157d62098 <unknown>\n#14 0x562157d62262 <unknown>\n#15 0x562157d73f34 <unknown>\n#16 0x7f821a694ac3 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/LTA_TESTS/LTA_TESTS/Test_Cases/conftest.py\", line 38, in get_webdriver\n    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 205, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 289, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 344, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"get_chrome_options","time":{"start":1707026950268,"stop":1707026950268,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"parentSuite","value":"Test_Cases"},{"name":"suite","value":"test_model"},{"name":"subSuite","value":"TestModel"},{"name":"host","value":"fv-az1116-70"},{"name":"thread","value":"2342-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"Test_Cases.test_model"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":16,"skipped":0,"passed":8,"unknown":0,"total":24},"items":[{"uid":"54bc071ccff971f0","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/55//#testresult/54bc071ccff971f0","status":"passed","time":{"start":1691742557595,"stop":1691742568976,"duration":11381}},{"uid":"b9b64f0ed2d3970a","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/53//#testresult/b9b64f0ed2d3970a","status":"passed","time":{"start":1691742112533,"stop":1691742124145,"duration":11612}},{"uid":"5ea4649ca995ff2a","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/49//#testresult/5ea4649ca995ff2a","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=115.0.5790.170)\nStacktrace:\n#0 0x5584ad44c613 <unknown>\n#1 0x5584ad178537 <unknown>\n#2 0x5584ad1503c1 <unknown>\n#3 0x5584ad1dc82f <unknown>\n#4 0x5584ad1ef856 <unknown>\n#5 0x5584ad1d7803 <unknown>\n#6 0x5584ad1ab68b <unknown>\n#7 0x5584ad1ac42e <unknown>\n#8 0x5584ad40dc28 <unknown>\n#9 0x5584ad411af7 <unknown>\n#10 0x5584ad41c01c <unknown>\n#11 0x5584ad412723 <unknown>\n#12 0x5584ad3e1457 <unknown>\n#13 0x5584ad436628 <unknown>\n#14 0x5584ad4367b7 <unknown>\n#15 0x5584ad445483 <unknown>\n#16 0x7f3fdefdfb43 <unknown>","time":{"start":1691688863459,"stop":1691688863462,"duration":3}},{"uid":"e249cfbf211a9551","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/48//#testresult/e249cfbf211a9551","status":"broken","statusDetails":"selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=115.0.5790.110)\nStacktrace:\n#0 0x560172680783 <unknown>\n#1 0x5601723ac917 <unknown>\n#2 0x5601723847b1 <unknown>\n#3 0x560172410bff <unknown>\n#4 0x560172423c26 <unknown>\n#5 0x56017240bbd3 <unknown>\n#6 0x5601723dfa7b <unknown>\n#7 0x5601723e081e <unknown>\n#8 0x560172641e98 <unknown>\n#9 0x560172645d67 <unknown>\n#10 0x56017265032c <unknown>\n#11 0x560172646993 <unknown>\n#12 0x560172615827 <unknown>\n#13 0x56017266a8a8 <unknown>\n#14 0x56017266aa36 <unknown>\n#15 0x5601726795f3 <unknown>\n#16 0x7f3736f0bb43 <unknown>","time":{"start":1691062137773,"stop":1691062137776,"duration":3}},{"uid":"98d9d158041cb712","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/47//#testresult/98d9d158041cb712","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=38175): Max retries exceeded with url: /session/715ec072add433f2f518c1e56e96c94c/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0988043ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1691061784401,"stop":1691061784404,"duration":3}},{"uid":"567b6013031020bd","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/46//#testresult/567b6013031020bd","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49359): Max retries exceeded with url: /session/7c8aec4adb4fb396c89f763efe720e8e/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe4e9696b30>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1691061387188,"stop":1691061387190,"duration":2}},{"uid":"60455353d93d499b","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/44//#testresult/60455353d93d499b","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x562f731f1783 <unknown>\n#1 0x562f72f1d917 <unknown>\n#2 0x562f72f48978 <unknown>\n#3 0x562f72f459c9 <unknown>\n#4 0x562f72f85a13 <unknown>\n#5 0x562f72f8515f <unknown>\n#6 0x562f72f7cbd3 <unknown>\n#7 0x562f72f50a7b <unknown>\n#8 0x562f72f5181e <unknown>\n#9 0x562f731b2e98 <unknown>\n#10 0x562f731b6d67 <unknown>\n#11 0x562f731c132c <unknown>\n#12 0x562f731b7993 <unknown>\n#13 0x562f73186827 <unknown>\n#14 0x562f731db8a8 <unknown>\n#15 0x562f731dba36 <unknown>\n#16 0x562f731ea5f3 <unknown>\n#17 0x7fb7173f7b43 <unknown>","time":{"start":1691060030531,"stop":1691060030531,"duration":0}},{"uid":"83f1c57f99575ed3","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/43//#testresult/83f1c57f99575ed3","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=45861): Max retries exceeded with url: /session/e5a689c724648f0d5308caa4a8bd27b1/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f87d2d8ebc0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1691045250826,"stop":1691045250828,"duration":2}},{"uid":"641959bd2c6871e6","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/43//#testresult/641959bd2c6871e6","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=59593): Max retries exceeded with url: /session/9568bcb038578a21277e87dd4550c15b/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff60f92b790>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1690989527395,"stop":1690989527398,"duration":3}},{"uid":"61309a10ee2b69e2","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/42//#testresult/61309a10ee2b69e2","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=45237): Max retries exceeded with url: /session/ac81092ea0663ab08d44674463c37387/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdf216c2ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1690988222741,"stop":1690988222744,"duration":3}},{"uid":"dc8d091fc4d2f302","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/41//#testresult/dc8d091fc4d2f302","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x563e81ead783 <unknown>\n#1 0x563e81bd9917 <unknown>\n#2 0x563e81c1831b <unknown>\n#3 0x563e81c18411 <unknown>\n#4 0x563e81c53674 <unknown>\n#5 0x563e81c38e2d <unknown>\n#6 0x563e81c510d9 <unknown>\n#7 0x563e81c38bd3 <unknown>\n#8 0x563e81c0ca7b <unknown>\n#9 0x563e81c0d81e <unknown>\n#10 0x563e81e6ee98 <unknown>\n#11 0x563e81e72d67 <unknown>\n#12 0x563e81e7d32c <unknown>\n#13 0x563e81e73993 <unknown>\n#14 0x563e81e42827 <unknown>\n#15 0x563e81e978a8 <unknown>\n#16 0x563e81e97a36 <unknown>\n#17 0x563e81ea65f3 <unknown>\n#18 0x7f31d0a67b43 <unknown>","time":{"start":1690985063488,"stop":1690985078914,"duration":15426}},{"uid":"824c618bf86219d5","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/38//#testresult/824c618bf86219d5","status":"broken","statusDetails":"ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_linux64.zip","time":{"start":1690975072419,"stop":1690975072419,"duration":0}},{"uid":"9978e4938db07f08","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/37//#testresult/9978e4938db07f08","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55b34f07c783 <unknown>\n#1 0x55b34eda8917 <unknown>\n#2 0x55b34edd3978 <unknown>\n#3 0x55b34edd09c9 <unknown>\n#4 0x55b34ee10a13 <unknown>\n#5 0x55b34ee1015f <unknown>\n#6 0x55b34ee07bd3 <unknown>\n#7 0x55b34eddba7b <unknown>\n#8 0x55b34eddc81e <unknown>\n#9 0x55b34f03de98 <unknown>\n#10 0x55b34f041d67 <unknown>\n#11 0x55b34f04c32c <unknown>\n#12 0x55b34f042993 <unknown>\n#13 0x55b34f011827 <unknown>\n#14 0x55b34f0668a8 <unknown>\n#15 0x55b34f066a36 <unknown>\n#16 0x55b34f0755f3 <unknown>\n#17 0x7f282c34ab43 <unknown>","time":{"start":1690974900306,"stop":1690974900306,"duration":0}},{"uid":"16fd6525a506e0c7","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/36//#testresult/16fd6525a506e0c7","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5618697cd783 <unknown>\n#1 0x5618694f9917 <unknown>\n#2 0x56186953831b <unknown>\n#3 0x561869538411 <unknown>\n#4 0x561869573674 <unknown>\n#5 0x561869558e2d <unknown>\n#6 0x5618695710d9 <unknown>\n#7 0x561869558bd3 <unknown>\n#8 0x56186952ca7b <unknown>\n#9 0x56186952d81e <unknown>\n#10 0x56186978ee98 <unknown>\n#11 0x561869792d67 <unknown>\n#12 0x56186979d32c <unknown>\n#13 0x561869793993 <unknown>\n#14 0x561869762827 <unknown>\n#15 0x5618697b78a8 <unknown>\n#16 0x5618697b7a36 <unknown>\n#17 0x5618697c65f3 <unknown>\n#18 0x7fdff123bb43 <unknown>","time":{"start":1690973704119,"stop":1690973719153,"duration":15034}},{"uid":"8fdbb3b99c972fc6","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/35//#testresult/8fdbb3b99c972fc6","status":"broken","statusDetails":"ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_linux64.zip","time":{"start":1690973260146,"stop":1690973260146,"duration":0}},{"uid":"adc7baf01a92f5a6","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/34//#testresult/adc7baf01a92f5a6","status":"broken","statusDetails":"selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x5606d2d87783 <unknown>\n#1 0x5606d2ab3917 <unknown>\n#2 0x5606d2af231b <unknown>\n#3 0x5606d2af2411 <unknown>\n#4 0x5606d2b2d674 <unknown>\n#5 0x5606d2b12e2d <unknown>\n#6 0x5606d2b2b0d9 <unknown>\n#7 0x5606d2b12bd3 <unknown>\n#8 0x5606d2ae6a7b <unknown>\n#9 0x5606d2ae781e <unknown>\n#10 0x5606d2d48e98 <unknown>\n#11 0x5606d2d4cd67 <unknown>\n#12 0x5606d2d5732c <unknown>\n#13 0x5606d2d4d993 <unknown>\n#14 0x5606d2d1c827 <unknown>\n#15 0x5606d2d718a8 <unknown>\n#16 0x5606d2d71a36 <unknown>\n#17 0x5606d2d805f3 <unknown>\n#18 0x7fe15aef0b43 <unknown>","time":{"start":1690972630861,"stop":1690972646299,"duration":15438}},{"uid":"c886b79cf7a937b9","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/33//#testresult/c886b79cf7a937b9","status":"broken","statusDetails":"ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_linux64.zip","time":{"start":1690971483261,"stop":1690971483261,"duration":0}},{"uid":"d717d58c91856cf5","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/32//#testresult/d717d58c91856cf5","status":"passed","time":{"start":1682507050034,"stop":1682507060429,"duration":10395}},{"uid":"a2b27af458db8266","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/32//#testresult/a2b27af458db8266","status":"passed","time":{"start":1682505639503,"stop":1682505649894,"duration":10391}},{"uid":"70f65d070c843378","reportUrl":"https://MaximKrivenko.github.io/LTA_TESTS/31//#testresult/70f65d070c843378","status":"passed","time":{"start":1682503871225,"stop":1682503881457,"duration":10232}}]},"tags":[]},"source":"7c52aaa85451e8fa.json","parameterValues":[]}